<?php
/**
 * JBZoo App is universal Joomla CCK, application for YooTheme Zoo component
 * @package     jbzoo
 * @version     2.x Pro
 * @author      JBZoo App http://jbzoo.com
 * @copyright   Copyright (C) JBZoo.com,  All rights reserved.
 * @license     http://jbzoo.com/license-pro.php JBZoo Licence
 * @coder       Alexander Oganov <t_tapak@yahoo.com>
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

/**
 * Class JBCartElementPriceImage
 */
class JBCartElementPriceImage extends JBCartElementPrice
{
    const IMAGE_EXISTS    = 1;
    const IMAGE_NO_EXISTS = 0;

    /**
     * @type JBImageHelper
     */
    protected $_jbimage = null;

    /**
     * @param App    $app
     * @param string $type
     * @param string $group
     */
    public function __construct($app, $type, $group)
    {
        parent::__construct($app, $type, $group); // TODO: Change the autogenerated stub

        $this->_jbimage = $this->app->jbimage;
    }

    /**
     * Check if element has value
     * @param array $params
     * @return bool
     */
    public function hasValue($params = array())
    {
        $img = $this->config->get('image', null);
        if (!empty($img)) {
            return true;
        }

        return true;
    }

    /**
     * Get elements search data
     * @return null
     */
    public function getSearchData()
    {
        $value    = JString::trim($this->getValue());
        $isExists = !empty($value) && JFile::exists(JPATH_ROOT . '/' . $value);

        if ($isExists) {
            return self::IMAGE_EXISTS;
        }

        return self::IMAGE_NO_EXISTS;
    }

    /**
     * @return mixed|null|string
     */
    public function edit()
    {
        if ($layout = $this->getLayout('edit.php')) {
            return self::renderEditLayout($layout, array(
                'value'  => $this->get('value', ''),
                'unique' => $this->htmlId(true)
            ));
        }

        return null;
    }

    /**
     * @param array $params
     * @return array|mixed|null|string
     */
    public function render($params = array())
    {
        $unique = $this->unique();

        if ($layout = $this->getLayout()) {
            return self::renderLayout($layout, array(
                'element' => $unique
            ));
        }

        return null;
    }

    /**
     * Get unique class
     * @return string
     */
    public function unique()
    {
        $image  = $this->config->get('image');
        $unique = $this->layout . '_' . $this->item_id;

        if (empty($image)) {
            return $unique;
        }

        return $unique . '_' . $image;
    }

    /**
     * @param $image
     * @param $params
     * @return JSONData|string
     */
    public function getImage($image, $params = array())
    {
        if (empty($image)) {
            return $image;
        }

        if (is_array($image)) {
            $image = $image['value'];
        }

        if (!$params) {
            return false;
        }

        $height      = (int)$params->get('height', 300);
        $width       = (int)$params->get('width', 400);
        $heightPopup = (int)$params->get('height_popup', 1280);
        $widthPopup  = (int)$params->get('width_popup', 800);

        $img = new stdClass();

        $url = $this->_jbimage->getUrl($image);
        if ($width || $height) {
            $url = $this->_jbimage->resize($image, $width, $height)->url;
        }

        $img->image = $url;
        if ($widthPopup || $heightPopup) {
            $url = $this->_jbimage->resize($image, $widthPopup, $heightPopup)->url;
        }

        $img->popup = $url;

        return !empty($img) ? $img : null;
    }

    /**
     * Get params for widget
     * @param array $params
     * @return array
     */
    public function interfaceParams($params = array())
    {
        $path = $this->getValue();

        return array(
            'related' => $this->unique(),
            'image'   => $this->getImage($path, $params)
        );
    }

    /**
     * Returns data when variant changes
     * @param array $params
     * @return null
     */
    public function renderAjax($params = array())
    {
        $path = $this->getValue();

        return $this->getImage($path, $params);
    }

    /**
     * Get elements value
     * @param string $key      Array key.
     * @param mixed  $default  Default value if data is empty.
     * @param bool   $toString A string representation of the value.
     * @return mixed|string
     */
    public function getValue($toString = false, $key = 'value', $default = null)
    {
        $value = parent::getValue($toString, $key, '');

        if (!isset($value{0}) && $element = $this->_getElement()) {
            $value = $element->get('file', $default);
        }

        return $value;
    }

    /**
     * Load elements css/js assets
     * @return $this
     */
    public function loadAssets()
    {
        $this->js(array(
            'cart-elements:price/image/assets/js/image.js',
            'jbassets:js/widget/media.js'
        ));

        return parent::loadAssets();
    }

    /**
     * Load elements css/js assets
     * @return $this
     */
    public function loadEditAssets()
    {
        $this->app->jbassets->js('jbassets:js/widget/media.js');

        return parent::loadEditAssets();
    }

    /**
     * Get related image element
     * @return ElementJBImage|bool
     */
    protected function _getElement()
    {
        $id = $this->config->get('image', false);
        if ($id && ($this->getJBPrice() && $item = $this->getJBPrice()->getItem())) {
            return $item->getElement($id);
        }

        return false;
    }

}
